export default [
    {
        id:1,
        count:"4",
        height:"50%",
        width:"50%",
    },
    {
        id:2,
        count:"6",
        height:"50%",
        width:"33.3%",
    },
    {
        id:3,
        count:"2",
        height:"100%",
        width:"50%", 
    },
    {
        id:4,
        count:"2",
        height:"50%",
        width:"100%",
    },
    {
        id:5,
        count:"4",
        height:"100%",
        width:"25%",
    },
    {
        id:6,
        count:"4",
        height:"25%",
        width:"100%",
    }
]